# -*- coding: utf-8 -*-
"""AreaCircle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lxO--gjwnsikLjE3lwq6whn-vHedF7tp
"""

import math #import math library so that you can access methods

radius_str=input("Enter the radius of your circle:")
radius_int=int(radius_str)#convert string into int

area=math.pi*(radius_int**2)
print("The area of the circle is",area)